//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_menu {
            get {
                return ResourceManager.GetString("About_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin .
        /// </summary>
        public static string Adminpage {
            get {
                return ResourceManager.GetString("Adminpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A barcode is an optical, machine-readable, representation of data; the data usually describes something
        ///                                about the object that carries the barcode.The barcode contains parallel black lines which are uniquely printed and
        ///                                contain some information. Each printed line is of varying width. The lines represents a number. You might find a
        ///                                number written below the barcode. The vertical lines represent the same number. E [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Barcode1 {
            get {
                return ResourceManager.GetString("Barcode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The concept for the barcode was developed by Norman Joseph Woodland, who drew a series of lines in the sand to represent
        ///                                Morse code, and Bernard Silver. A patent was granted in 1966 and NCR became the first company to develop a commercial scanner
        ///                                to read barcode symbology. A pack of Wrigley’s gum was the first item ever scanned, at Marsh’s supermarket in Troy, Ohio, NCR’s hometown..
        /// </summary>
        public static string Barcode2 {
            get {
                return ResourceManager.GetString("Barcode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are mainly two types of barcode. The first one is 1-D barcode or one-dimensional barcode. In 1-D barcode
        ///                                the data is represented using only parallel lines of varying width. Sometime a number is also found below the encoded lines.
        ///                                The second one is 2-D barcode. In 2-D barcode, the data is represented using dots, rectangles, hexagons and other geometrical
        ///                                shapes. The 2-D barcodes later got different names  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Barcode3 {
            get {
                return ResourceManager.GetString("Barcode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might find the barcode scanners in shopping malls or any retail stores. The working of barcode scanners is simple.
        ///                                The barcode scanner emits red light. This light is then thrown onto the black and white stripes. The amount of light reflected by these
        ///                                lines identifies the code.
        ///
        ///                                Another technology uses digital camera to identify the code. A photograph of the code is taken and the code in photo is processed [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Barcode4 {
            get {
                return ResourceManager.GetString("Barcode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARCODE HISTORY.
        /// </summary>
        public static string BarcodeHistory {
            get {
                return ResourceManager.GetString("BarcodeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one click to scan.
        /// </summary>
        public static string click_menu {
            get {
                return ResourceManager.GetString("click_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact_menu {
            get {
                return ResourceManager.GetString("Contact_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate_menu {
            get {
                return ResourceManager.GetString("Generate_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_menu {
            get {
                return ResourceManager.GetString("Home_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW DOES BARCODE SCANER WORK ?.
        /// </summary>
        public static string HowDoesBarcodeWork {
            get {
                return ResourceManager.GetString("HowDoesBarcodeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language .
        /// </summary>
        public static string LanguageCheng {
            get {
                return ResourceManager.GetString("LanguageCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        public static string Login_successful {
            get {
                return ResourceManager.GetString("Login_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout_menu {
            get {
                return ResourceManager.GetString("Logout_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_menu {
            get {
                return ResourceManager.GetString("Register_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan_menu {
            get {
                return ResourceManager.GetString("Scan_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin.
        /// </summary>
        public static string Signin_menu {
            get {
                return ResourceManager.GetString("Signin_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string Signup_menu {
            get {
                return ResourceManager.GetString("Signup_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit  message.
        /// </summary>
        public static string submitmessage {
            get {
                return ResourceManager.GetString("submitmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE OF BARCODE.
        /// </summary>
        public static string TypeOfBarcode {
            get {
                return ResourceManager.GetString("TypeOfBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Userneme {
            get {
                return ResourceManager.GetString("Userneme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT IS BARCODE ?.
        /// </summary>
        public static string whatisbarcode {
            get {
                return ResourceManager.GetString("whatisbarcode", resourceCulture);
            }
        }
    }
}
